services:
  # Backend - Spring Boot API
  - type: web
    name: rgbradford-backend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./backend/dockerfile
    dockerContext: ./backend
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      # Azure SQL Server connection
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false  # Set in Render dashboard
      - key: DATABASE_PASSWORD
        sync: false  # Set in Render dashboard as secret
      - key: DATABASE_DRIVER
        value: com.microsoft.sqlserver.jdbc.SQLServerDriver
      # JPA/Hibernate configuration
      - key: JPA_DIALECT
        value: org.hibernate.dialect.SQLServerDialect
      - key: JPA_DDL_AUTO
        value: validate
      - key: JPA_SHOW_SQL
        value: false
      # Server configuration - PORT is automatically set by Render
      # JWT Secret
      - key: JWT_SECRET
        sync: false
      # Logging
      - key: LOG_LEVEL
        value: INFO
      - key: SPRING_LOG_LEVEL
        value: INFO
      - key: APP_LOG_LEVEL
        value: INFO
      # CORS
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      # File upload limits
      - key: MAX_FILE_SIZE
        value: 10MB
      - key: MAX_REQUEST_SIZE
        value: 10MB

  # Frontend - React + Nginx
  - type: web
    name: rgbradford-frontend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: rgbradford-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: NODE_ENV
        value: production